// https://github.com/sendgrid/sendgrid-nodejs
import sendgrid from "@sendgrid/mail";
import path from "path";
import dotenv from "dotenv";

dotenv.config({ path: path.resolve(__dirname, "./.env.local") });
sendgrid.setApiKey(process.env.SENDGRID_API_KEY ?? ``);

const senderIdentity = `avi.mehenwal@dility.io`;

const msg = {
  from: senderIdentity,
  template_id: "d-9a759651728042f79daaaa74cdeb2a0c",
  personalizations: [
    {
      to: [{ email: "avi.mehanwal@gmail.com" }],
      // to: [
      //   { email: "avi.mehanwal@gmail.com" },
      //   { email: 'laura.olivarez@dility.io' },
      //   { email: 'ahmed@dility.io' },
      // ],
      dynamic_template_data: {
        workshop_owner: "Avi Mehenwal",
        workshop_name: "My-awesome-workshop",
        workshop_date: "32-August-2022",
      },
      content: [
        {
          type: "text/html",
          value: "text/html",
        },
      ],
    },
  ],

  // text: "and easy to do anywhere, even with Node.js",
  // html: "<h1>Machine generated email</h1><p>Hello! This is a email generated by code :)</p><p>yay!</p>",
};

sendgrid
  // @ts-ignore
  .send(msg)
  .then(() => {
    console.log("Email sent");
  })
  .catch((error) => {
    console.error(error);
  });

/* PAIN POINTS

- email template designing


*/
