// https://github.com/sendgrid/sendgrid-nodejs
import sendgrid from "@sendgrid/mail"
import path from "path"
import dotenv from "dotenv"

dotenv.config({ path: path.resolve(__dirname, "./.env.local") });
sendgrid.setApiKey(process.env.SENDGRID_API_KEY ?? ``)

const senderIdentity = `avi.mehenwal@dility.io`

const msg = {
  from   : senderIdentity,
  html   : '<h1>Machine generated email</h1><p>Hello! This is a email generated by code :)</p><p>yay!</p>',
  subject: 'Dility: automated email',
  text   : 'and easy to do anywhere, even with Node.js',
  to     : 'avi.mehanwal@gmail.com',
  // to     : ['ahmed@dility.io', 'laura.olivarez@dility.io', 'avi.mehenwal@dility.io'],
}

sendgrid.send(msg)
  .then(() => {
    console.log('Email sent')
  })
  .catch((error) => {
    console.error(error)
  })
