// using Twilio SendGrid's v3 Node.js Library
// https://github.com/sendgrid/sendgrid-nodejs

const sgMail = require('@sendgrid/mail')
sgMail.setApiKey(process.env.SENDGRID_API_KEY)

const senderIdentity = `avi.mehenwal@dility.io`

const msg = {
  from   : senderIdentity,
  html   : '<h1>Machine generated email</h1><p>Hello! This is a email generated by code :)</p><p>yay!</p>',
  subject: 'Dility: automated email',
  text   : 'and easy to do anywhere, even with Node.js',
  to     : 'avi.mehanwal@gmail.com',
  // to     : ['ahmed@dility.io', 'laura.olivarez@dility.io', 'avi.mehenwal@dility.io'],
}
sgMail
  .send(msg)
  .then(() => {
    console.log('Email sent')
  })
  .catch((error) => {
    console.error(error)
  })
