name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        echo "${{ secrets.AVI_GITHUB_PAT }}" | docker login ghcr.io -u avimehenwal --password-stdin
        docker build --file apps/ui/Dockerfile --tag ghcr.io/dility/ui apps/ui      
        docker push ghcr.io/dility/ui
