name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: |
        docker build --file apps/ui/Dockerfile --tag ghcr.io/dility/ui:${{ github.sha }} apps/ui      
    
    - name: Login & Push docker image on ghcr container registry
      run: |
        echo "${{ secrets.AVI_GITHUB_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/dility/ui:${{ github.sha }}

